doc(test): Add the test command line in readme and how to use it
dan-online/bunnycdn-stream pull request #140
Opened 2023-05-02 19:07 UTC by vladimirkosmala

## 📑 Description
I needed to read the code to understand how to run the tests.
This commit will directly show in the README how to set the Bunny's credentials.

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [ ] All the tests have passed

2023-05-03 08:13 UTC, dan-online commented on README.md
> +The project is tested with vitest and requires you to have a test library on your BunnyCDN account to send commands to the Bunny API. Warning: all videos will be deleted during testing.
```suggestion
The project is tested with `vitest` and requires you to have a library on your BunnyCDN account to send commands to the Bunny API. 

> Warning: all videos will be deleted during testing.

### Keys
```

2023-05-03 08:15 UTC, dan-online requested changes
Some phrasing and formatting changes needed

2023-05-03 08:15 UTC, dan-online commented on README.md
> +Also, IGNORE_PRUNE=1 can be used to keep the video in Bunny at the end of the tests for further manual checking.
```suggestion
Also, `IGNORE_PRUNE=1` can be used to keep the testing video at the end of the tests for further manual checking.
```

2023-05-03 08:15 UTC, dan-online commented on README.md
> +The project is tested with vitest and requires you to have a test library on your BunnyCDN account to send commands to the Bunny API. Warning: all videos will be deleted during testing.
```suggestion
The project is tested with `vitest` and requires you to have a library on your BunnyCDN account to send commands to the Bunny API. 

> Warning: all videos will be deleted during testing.

### Keys
```

2023-05-03 22:18 UTC, vladimirkosmala commented
> Some phrasing and formatting changes needed

This looks fine

2023-05-04 15:20 UTC, dan-online approved these changes

2023-05-04 15:20 UTC, merged